name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  http: ^0.13.6
  video_player: ^2.9.2
  web_socket_channel: ^3.0.1
  window_manager: ^0.4.2
  flutter_mjpeg: ^2.0.4
  flutter_dotenv: ^5.2.1
  pdfx: ^2.8.0
  pdf: ^3.11.1
  dio: ^5.7.0
  file_picker: ^8.1.3
  path: ^1.9.0
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/main_page_image.png
    - lib/images/trabalhadores_image.png